name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
     - uses: Platane/snk@master
       with:
          github_user_name: Lucas-Duarte-dev
          svg_out_path: dist/github-contribution-grid-snake.svg
     - uses: crazy-max/ghaction-github-pages@v2.1.3
       with:
          target_branch: output
          build_dir: dist
